#!/usr/bin/env bash
# This displays to infinity and beyond
# With a sleep 2 in between each iteration.
# Also displays I am invincible!!! when receiving a SIGTERM signal

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
